services:
  nginx:
    image: nginx:latest
    env_file:
      - ./env/.env.prod
    ports:
      - 443:443
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/pki/tls/private:/etc/pki/tls/private
      - ./env/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - api
    restart: 'always'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env.prod
    expose:
      - 8000
    restart: 'always'
