version: '3.1'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
