services:
  nginx:
    image: nginx:latest
    env_file:
      - ./env/.env.prod
    ports:
      - 8001:8001
    volumes:
      - ./env/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - api
    restart: 'always'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./env/.env.prod
    restart: 'always'

  db:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgres/:/var/lib/pgsql/algorithms_data
    environment:
      - POSTGRES_DB=tf_algorithms
      - POSTGRES_USER=tf_algorithms_db_user
      - POSTGRES_PASSWORD=tf_algorithms_db_password
    restart: 'always'
