services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: gunicorn api.api.wsgi:application --bind 0.0.0.0:8000
        expose:
            - 8000
        restart: 'on-failure'
