from datetime import datetime
import json
import os
from os import path
from typing import List, Dict, Any

import git

from api.models.team_set import TeamSet


class SimulationCache:
    """
    This class is used to cache the results of a simulation, which is a List[TeamSet], where each element of the list is a different run.
    All TeamSets should have been generated by the same algorithm (with the same settings).
    It uses the cache_key to generate a file with the results of the simulation.
    """

    def __init__(self, cache_key: str) -> None:
        self.cache_key = cache_key

    def exists(self) -> bool:
        """
        Checks if the cache_key is in the cache.
        """
        return path.exists(self._get_file())

    def get_teams(self) -> List[TeamSet]:
        """
        Gets the simulation results from the cache.
        """
        pass

    def get_metadata(self) -> Dict[str, Any]:
        """
        Gets the metadata associated with the simulation results from the cache.
        """
        pass

    def save(
        self, simulation_results: List[TeamSet], metadata: Dict[str, Any] = None
    ) -> None:
        """
        Puts the simulation results into the cache.
        Overwrites any existing cache with the same cache_key.
        """

        # Get metadata
        metadata = metadata or {}
        metadata["timestamp"] = datetime.now().isoformat()
        # Get latest commit hash from main. This is so that we can track which commit generated the cache and go back to the code that generated it if needed. Assumes that this code is run from main. Would then be accessible at https://github.com/Teamable-Analytics/algorithms/commit/<commit_hash>
        metadata["commit_hash"] = git.Repo(
            search_parent_directories=True
        ).head.object.hexsha

        # Get stripped down version of TeamSets
        # TODO: Once Seth's code is merged
        stripped_team_sets = []

        # Convert to JSON
        json_team_sets = json.dumps(stripped_team_sets)

        # Write to file
        with open(self._get_file(), "w+") as file:
            file.write(json_team_sets)

    def clear(self) -> None:
        """
        Clears the cache.
        """
        pass

    def _get_file(self) -> str:
        """
        Gets the file associated with the cache_key.
        """

        # Get cache directory
        current_dir = path.dirname(__file__)
        cache_dir = path.abspath(path.join(current_dir, "..", "..", "cache"))

        # Create cache directory if it doesn't exist
        if not path.exists(cache_dir):
            os.makedirs(cache_dir)

        # Get file
        return path.join(cache_dir, self.cache_key + ".json")
