name: Run Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is the latest version of macOS Intel, macos-latest is the latest version of macOS ARM
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install MacOS dependency
        run: |
          if [ "$RUNNER_OS" == "MacOS" ]; then
            brew install postgresql
            export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
            export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib -L${HOME}/.pyenv/versions/3.8.10/lib"
            python -m pip install psycopg2-binary
          fi
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && python -m pip install -r requirements.txt

  lint:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip && python -m pip install black[jupyter]==23.7.0
      - name: Lint with Black
        run: |
          python -m black . --check

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -m unittest discover tests
